# Generated by Django 3.1.6 on 2021-02-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0002_auto_20210210_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='URL'),
        ),
    ]
