# Generated by Django 3.1.6 on 2021-02-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0004_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип издания',
                'verbose_name_plural': 'Типы изданий',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_edition', models.CharField(max_length=100, verbose_name='Название газеты')),
                ('start_data', models.DateField(verbose_name='Дата начала подписки')),
                ('end_data', models.DateField(verbose_name='Дата конца подписки')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newspapers.typeofedition')),
                ('worker', models.ManyToManyField(to='newspapers.Worker')),
            ],
            options={
                'verbose_name': 'Издание',
                'verbose_name_plural': 'Издания',
                'ordering': ['name_of_the_edition'],
            },
        ),
    ]
